--instruccion ddl restante
-- modificacion de tablas: alter

ALTER TABLE NOMBRE_TABLA
    LO QUE NECESITO MODIFICAR;


MODFICICACIONES PERMITIDAS SON:
    AGREGAR CAMPOS: ADD NOMBRE_CAMPO TIPO_DATO;
    BORRAR CAMPO: DROP COLUMN NOMBRE_CAMPO_A_BORRAR;
    MODIFICAR CAMPOS: MODIFY NOMBRE_CAMPO TIPO_DATO;
    AGREGAR RESTRICCIONES: ADD CONSTRAINT RESTRICCION_CORRESPONDIENTE;
    MODIFICAR RESTRICCIONES: MODIFY CONSTRAINT NOMBRE_RESTRICCION ENABLE/DISABLE;
