
/*
aplicarles almenos 5 intos a cada tabla 
*/
------------------------------------BORRADO DE TABLAS

DROP TABLE RAYV_DETALLE_LIBRO_AUTOR;
DROP TABLE RAYV_AUTORES;
DROP TABLE RAYV_DETALLE_PRESTAMO_EJEMPLAR;
DROP TABLE RAYV_EJEMPLARES;
DROP TABLE RAYV_LIBROS;
DROP TABLE RAYV_EDITORIALES;
DROP TABLE RAYV_PRESTAMOS;
DROP TABLE RAYV_USUARIOS;
DROP TABLE RAYV_CIUDADES;
DROP TABLE RAYV_REGIONES;

------------------------------------CREACION DE TABLAS
--REPLICANDO LA TABLA DE LA BIBLIOTECA NORMALIZADA Q ESTA EN LA UNIDAD 2 DEL LMS

CREATE TABLE RAYV_EDITORIALES(
    COD_EDITORIAL NUMBER,
    NOMBRE_EDITORIAL VARCHAR2(100),
    CONSTRAINT PK_RAYV_EDITORIALES PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE RAYV_LIBROS(
    COD_LIBRO NUMBER,
    ISBN_LIBRO NUMBER,
    TITULO_LIBRO VARCHAR2(300),
    NRO_PAGINAS_LIBRO NUMBER,
    COD_EDITORIAL NUMBER,
    CONSTRAINT PK_RAYV_LIBROS PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_RAYV_LIBROS_EDITORIALES FOREIGN KEY(COD_EDITORIAL) REFERENCES RAYV_EDITORIALES(COD_EDITORIAL)
);

CREATE TABLE RAYV_AUTORES(
    COD_AUTOR NUMBER,
    NOMBRE_AUTOR VARCHAR2(200),
    APELLIDO1_AUTOR VARCHAR2(80),
    APELLIDO2_AUTOR VARCHAR2(80),
    CONSTRAINT PK_AUTORES PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE RAYV_DETALLES_LIBRO_AUTOR(
    COD_AUTOR NUMBER,
    COD_LIBRO NUMBER,
    CONSTRAINT PK_DETALLES_LIBRO_AUTOR PRIMARY KEY (COD_AUTOR,COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_LIBROS FOREIGN KEY (COD_LIBRO) REFERENCES RAYV_LIBROS(COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_AUTORES FOREIGN KEY (COD_AUTOR) REFERENCES RAYV_AUTORES(COD_AUTOR)
);

CREATE TABLE RAYV_EJEMPLARES(
    COD_EJEMPLAR NUMBER,
    COD_LIBRO NUMBER,
    LOCALIZACION VARCHAR2(6),
    CONSTRAINT PK_RAYV_EJEMPLARES PRIMARY KEY (COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_EJEMPLARES_LIBROS FOREIGN KEY(COD_LIBRO) REFERENCES RAYV_LIBROS(COD_LIBRO)
);

CREATE TABLE RAYV_REGIONES(
	COD_REGION NUMBER,
	NOMBRE_REGION VARCHAR2(30),
	CONSTRAINT PK_RAYV_REGIONES PRIMARY KEY(COD_REGION)
);

CREATE TABLE RAYV_CIUDADES(
	COD_CIUDAD NUMBER,
	NOMBRE_CIUDAD VARCHAR2(30),
	COD_REGION NUMBER,
	CONSTRAINT PK_RAYV_CIUDADES PRIMARY KEY(COD_CIUDAD),
	CONSTRAINT FK_RAYV_CUIUDADES_REGIONES FOREIGN KEY(COD_REGION) REFERENCES RAYV_REGIONES(COD_REGION)
);

CREATE TABLE RAYV_USUARIOS(
	COD_USUARIO NUMBER,
	NOMBRE_USUARIO VARCHAR2(200),
	APELLIDO1_USUARIO VARCHAR2(80),
	APELLIDO2_USUARIO VARCHAR2(80),
	TELEFONO_USUARIO NUMBER,
	DIRECCION_USUARIO_CALLE VARCHAR2(50),
	DIRECCION_USUARIO_NUMERO NUMBER,
	COD_CIUDAD NUMBER,
	CONSTRAINT PK_RAYV_USUARIOS PRIMARY KEY(COD_USUARIO),
	CONSTRAINT FK_RAYV_USUARIOS_CIUDADES FOREIGN KEY(COD_CIUDAD) REFERENCES RAYV_CIUDADES(COD_CIUDAD)
);

CREATE TABLE RAYV_PRESTAMOS(
	COD_PRESTAMO NUMBER,
	FECHA_PRESTAMO DATE,
	FECHA_DEVOLUCION DATE,
	COD_USUARIO NUMBER,
	CONSTRAINT PK_RAYV_PRESTAMO PRIMARY KEY(COD_PRESTAMO),
	CONSTRAINT FK_RAYV_PRESTAMO_USUARIOS FOREIGN KEY(COD_USUARIO) REFERENCES RAYV_USUARIOS(COD_USUARIO)
);

CREATE TABLE RAYV_DETALLE_PRESTAMO_EJEMPLAR(
	COD_PRESTAMO NUMBER,
	COD_EJEMPLAR NUMBER,
	CONSTRAINT PK_RAYV_DETALLE_PRESTAMO_EJEMPLAR PRIMARY KEY(COD_PRESTAMO,COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_DETALLE_PRESTAMO_EJEMPLAR_EJEMPALRES FOREIGN KEY(COD_EJEMPLAR) REFERENCES RAYV_EJEMPLARES(COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_DETALLE_PRESTAMO_EJEMPLAR_PRESTAMOS FOREIGN KEY(COD_PRESTAMO) REFERENCES RAYV_PRESTAMOS(COD_PRESTAMO)
);

/*
INSERT PARA EDITORIALES
*/

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
    VALUES(1,'');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
    VALUES(2,'');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
    VALUES(3,'');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
    VALUES(,'');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
    VALUES(,'');