/*
NOMBRE_ESTUDIANTE: CARLOS CASTRO BUSTAMANTE
NOMBRE_PROFESOR: CARLOS CASTRO BUSTAMANTE
FECHA: 11-06
NOMBRE_RAMO: MODELAMIENTO DE DATOS
SECCIÓN: 2
*/
-------------------------------BORRADO DE TABLAS-------------------------------------
DROP TABLE CACB_DETALLE_LIBRO_AUTOR;
DROP TABLE CACB_AUTORES;
DROP TABLE CACB_DETALLE_PRESTAMO_EJEMPLAR;
DROP TABLE CACB_EJEMPLARES;
DROP TABLE CACB_LIBROS;
DROP TABLE CACB_EDITORIALES;
DROP TABLE CACB_PRESTAMOS;
DROP TABLE CACB_USUARIOS;
DROP TABLE CACB_CIUDADES;
DROP TABLE CACB_REGIONES;
-------------------------------CREACION DE TABLAS------------------------------------
CREATE TABLE CACB_EDITORIALES(
	COD_EDITORIAL NUMBER,
	NOMBRE_EDITORIAL VARCHAR2(100),
	CONSTRAINT PK_CACB_EDITORIALES PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE CACB_LIBROS(
	COD_LIBRO NUMBER,
	ISBN_LIBRO NUMBER,
	TITULO_LIBRO VARCHAR2(300),
	NRO_PAGINAS_LIBRO NUMBER,
	COD_EDITORIAL NUMBER,
	CONSTRAINT PK_CACB_LIBROS PRIMARY KEY(COD_LIBRO),
	CONSTRAINT FK_CACB_LIBROS_EDITORIALES FOREIGN KEY(COD_EDITORIAL) REFERENCES CACB_EDITORIALES(COD_EDITORIAL)
);

CREATE TABLE CACB_AUTORES(
	COD_AUTOR NUMBER,
	NOMBRE_AUTOR VARCHAR2(200),
	APELLIDO1_AUTOR VARCHAR2(80),
	APELLIDO2_AUTOR VARCHAR2(80),
	CONSTRAINT PK_CACB_AUTORES PRIMARY KEY(COD_AUTOR)
);

CREATE TABLE CACB_DETALLE_LIBRO_AUTOR(
	COD_AUTOR NUMBER,
	COD_LIBRO NUMBER,
	CONSTRAINT PK_DETALLE_LIBRO_AUTOR PRIMARY KEY(COD_AUTOR,COD_LIBRO),
	CONSTRAINT FK_CACB_DETALLE_LIBRO_AUTOR_AUTORES FOREIGN KEY(COD_AUTOR) REFERENCES CACB_AUTORES(COD_AUTOR),
	CONSTRAINT FK_CACB_DETALLE_LIBRO_AUTOR_LIBROS FOREIGN KEY(COD_LIBRO) REFERENCES CACB_LIBROS(COD_LIBRO)
);

CREATE TABLE CACB_EJEMPLARES(
	COD_EJEMPLAR NUMBER,
	COD_LIBRO NUMBER,
	LOCALIZACION VARCHAR2(6),
	CONSTRAINT PK_CACB_EJEMPLARES PRIMARY KEY(COD_EJEMPLAR),
	CONSTRAINT FK_CACB_EJEMPLARES_LIBROS FOREIGN KEY(COD_LIBRO) REFERENCES CACB_LIBROS(COD_LIBRO)
);

CREATE TABLE CACB_REGIONES(
	COD_REGION NUMBER, 
	NOMBRE_REGION VARCHAR2(30),
	CONSTRAINT PK_CACB_REGIONES PRIMARY KEY(COD_REGION)
);

CREATE TABLE CACB_CIUDADES(
	COD_CIUDAD NUMBER,
	NOMBRE_CIUDAD VARCHAR2(30),
	COD_REGION NUMBER,
	CONSTRAINT PK_CACB_CIUDADES PRIMARY KEY(COD_CIUDAD),
	CONSTRAINT FK_CACB_CUIUDADES_REGIONES FOREIGN KEY(COD_REGION) REFERENCES CACB_REGIONES(COD_REGION)
);

CREATE TABLE CACB_USUARIOS(
	COD_USUARIO NUMBER,
	NOMBRE_USUARIO VARCHAR2(200),
	APELLIDO1_USUARIO VARCHAR2(80),
	APELLIDO2_USUARIO VARCHAR2(80),
	TELEFONO_USUARIO NUMBER,
	DIRECCION_USUARIO_CALLE VARCHAR2(50),
	DIRECCION_USUARIO_NUMERO NUMBER,
	COD_CIUDAD NUMBER,
	CONSTRAINT PK_CACB_USUARIOS PRIMARY KEY(COD_USUARIO),
	CONSTRAINT FK_CACB_USUARIOS_CIUDADES FOREIGN KEY(COD_CIUDAD) REFERENCES CACB_CIUDADES(COD_CIUDAD)
);

CREATE TABLE CACB_PRESTAMOS(
	COD_PRESTAMO NUMBER,
	FECHA_PRESTAMO DATE,
	FECHA_DEVOLUCION DATE,
	COD_USUARIO NUMBER,
	CONSTRAINT PK_CACB_PRESTAMO PRIMARY KEY(COD_PRESTAMO),
	CONSTRAINT FK_CACB_PRESTAMO_USUARIOS FOREIGN KEY(COD_USUARIO) REFERENCES CACB_USUARIOS(COD_USUARIO)
);

CREATE TABLE CACB_DETALLE_PRESTAMO_EJEMPLAR(
	COD_PRESTAMO NUMBER,
	COD_EJEMPLAR NUMBER,
	CONSTRAINT PK_CACB_DETALLE_PRESTAMO_EJEMPLAR PRIMARY KEY(COD_PRESTAMO,COD_EJEMPLAR),
	CONSTRAINT FK_CACB_DETALLE_PRESTAMO_EJEMPLAR_EJEMPALRES FOREIGN KEY(COD_EJEMPLAR) REFERENCES CACB_EJEMPLARES(COD_EJEMPLAR),
	CONSTRAINT FK_CACB_DETALLE_PRESTAMO_EJEMPLAR_PRESTAMOS FOREIGN KEY(COD_PRESTAMO) REFERENCES CACB_PRESTAMOS(COD_PRESTAMO)
);