create table RAYV_CLIENTE(
    NRO_CLIENTE NUMBER,
    NOMBRE_CLIENTE VARCHAR2(50),
    APELLIDO1_CLIENTE VARCHAR2(30),
    APELLIDO2_CLIENTE VARCHAR2(30),
    DIRECCION_CLIENTE VARCHAR2(80),
    SALDO NUMBER,
    CREDITO NUMBER,
    DESCUENTO NUMBER,
    CONSTRAINT PK_CACB_CLIENTES PRIMARY KEY (NRO_CLIENTE)
);