/*
NOMBRE_ESTUDIANTE: RICARDO ANTONIO YAÑEZ VEGA
NOMBRE_PROFESOR: CARLOS CASTRO BUSTAMANTE
FECHA: 06-11
NOMBRE_RAMO: MODELAMIENTO DE DATOS
SECCION: 2

*/
------------------------------------BORRADO DE TABLAS







------------------------------------CREACION DE TABLAS
--REPLICANDO LA TABLA DE LA BIBLIOTECA NORMALIZADA Q ESTA EN LA UNIDAD 2 DEL LMS

CREATE TABLE RAYV_EDITORIALES(
    COD_EDITORIAL NUMBER,
    NOMBRE_EDITORIAL VARCHAR2(100)
    CONSTRAINT PK_RAYV_EDITORIALES PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE RAYV_LIBROS(
    COD_LIBRO NUMBER,
    ISBN_LIBRO NUMBER,
    TITULO_LIBRO VARCHAR2(300),
    NRO_PAGINAS_LIBRO NUMBER,
    COD_EDITORIAL NUMBER,
    CONSTRAINT PK_RAYV_LIBROS PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_RAYV_LIBROS_EDITORIALES FOREIGN KEY(COD_EDITORIAL) REFERENCES RAYV_EDITORIALES(COD_EDITORIAL)
);

CREATE TABLE RAYV_AUTORES(
    COD_AUTOR NUMBER,
    NOMBRE_AUTOR VARCHAR2(200),
    APELLIDO1_AUTOR VARCHAR2(80),
    APELLIDO2_AUTOR VARCHAR2(80),
    CONSTRAINT PK_AUTORES PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE RAYV_DETALLES_LIBRO_AUTOR(
    COD_AUTOR NUMBER,
    COD_LIBRO NUMBER,
    CONSTRAINT PK_DETALLES_LIBRO_AUTOR PRIMARY KEY (COD_AUTOR),
    CONSTRAINT PK_DETALLES_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_LIBROS FOREIGN KEY (COD_LIBRO) REFERENCES RAYV_LIBROS(COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_AUTORES FOREIGN KEY (COD_AUTOR) REFERENCES RAYV_AUTORES(COD_AUTOR)
);

CREATE TABLE RAYV_REGION(

)