



SUELDO_OBTENIDO = SELECT SALARY FROM OEHR_EMPLOYEES WHERE (EMPLOYEE_ID 101);

CREATE OR REPLACE FUNCTION CACB_OBTENER_SUELDO(
    EMPLOYEE_ID_F NUMBER
)

IS
    SUELDO_OBTENIDO NUMBER :=0;
BEGIN
    SELECT SALARY INTO SUELDO_OBTENIDO
    FROM OEHR_EMPLOYEES
    WHERE EMPLOYEE_ID = COD_USUARIO_F;
    IF (SUELDO_OBTENIDO IS NULL)THEN
        SUELDO_OBTENIDO :=0;
    END IF;
    RETURN SUELDO_OBTENIDO;
END;
