-- QUISIERA SABER DATOS ACERCA DE LOS TRABAJADORES QUE GANAN MÁS DINERO
-- QUE ABEL (APELLIDO).

SELECT *
FROM OEHR_EMPLOYEES
WHERE SALARY > 'ABEL';

-- HAY UNA INCOSISTENCIA
-- QUE NO PODEMOS COMPARAR UN SALARY, QUE ES UN VALOR NUMÉRICO, CON LAST_NAME QUE ES UN VALOR
-- ALFANUMÉRICO.

-- CÓMO SE RESUELVE ESTO: PRIMERO, BUSCANDO CUÁNTO GANA ABEL Y LUEGO INCORPORANDO ESE
-- SUELDO EN LA CONSULTA ANTERIOR.

SELECT SALARY
FROM OEHR_EMPLOYEES
WHERE UPPER(LAST_NAME) = 'ABEL';

SELECT *
FROM OEHR_EMPLOYEES
WHERE SALARY > 11000;


-- SUBCONSULTAS

SELECT QUE QUIERO MOSTRAR
FROM DE DONDE LO VOY A SACAR
WHERE FILTRO

-- EN UNA SUBCONSULTA EL FILTRO SUELE COMPORTARSE DE LA SIGUIENTE FORMA:
-- VARIABLE = (SELECT...)

-- ESTE COMPORTAMIENTO ESTÁ SUJETO A OPERADORES DE COMPARACIÓN
-- PARA SUBCONSULTAS, QUE DEVUELVEN UN VALOR Y OTROS OPERADORES
-- QUE DEVUELVEN MULTIPLES VALORES.

-- 1. LOS OPERADORES IGUALITARIOS FUNCIONAN CON VALORES ÚNICOS.
-- 2. SI LOS QUIERO OCUPAR REQUIERO UTILIZAR ANTES LOS OPERADORES IN, ANY, ALL

-- ¿CÓMO RESUELVO ESTO CON SÓLO UNA CONSULTA?

SELECT *
FROM OEHR_EMPLOYEES
WHERE SALARY > (SELECT SALARY
				FROM OEHR_EMPLOYEES
				WHERE UPPER(LAST_NAME) = 'ABEL');


-- QUISIERA SABER COD_TRABAJADOR, APELLIDO, NOMBRE_DEPARTAMENTO Y CIUDAD DE TODOS 
-- AQUELLOS TRABAJADORES QUE TENGAN UN SUELDO SUPERIOR AL DE WHALEN

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMEN_NAME, CITY
FROM OEHR_EMPLOYEES JOIN OEHR_DEPARTMENTS USING(DEPARTMENT_ID)
	JOIN OEHR_LOCATIONS USING(LOCATION_ID = LOCATION_ID)
WHERE SALARY > (SELECT SALARY
				FROM OEHR_EMPLOYEES
				WHERE UPPER(LAST_NAME) = 'WHALEN');


SELECT E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM OEHR_EMPLOYEES E JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
	JOIN OEHR_LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
WHERE E.SALARY > (SELECT SALARY
				FROM OEHR_EMPLOYEES
				WHERE UPPER(LAST_NAME) = 'WHALEN');

-- QUISIERA SABER COD_TRABAJADOR, APELLIDO, NOMBRE_DEPARTAMENTO Y CIUDAD DE TODOS 
-- AQUELLOS TRABAJADORES QUE GANEN SUELDOS QUE VARÍEN ENTRE LOS SUELDOS DE NAYER Y 
-- WHALEN


SELECT E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM OEHR_EMPLOYEES E JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
	JOIN OEHR_LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
WHERE E.SALARY BETWEEN (SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME) = 'NAYER') AND (SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME) = 'WHALEN');

-- QUISIERA SABER EL APELLIDO, NOMBRE_CARGO Y SUELDO DE TODOS AQUELLOS TRABAJADORES
-- QUE TENGAN UN CARGO COMO EL DE TAYLOR Y SU SUELDO SEA MAYOR QUE EL DE TAYLOR

SELECT E.LAST_NAME, J.JOB_TITLE, E.SALARY
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON(E.JOB_ID = J.JOB_ID)
WHERE E.JOB_ID IN(SELECT JOB_ID
					FROM OEHR_EMPLOYEES
					WHERE UPPER(LAST_NAME) = 'TAYLOR')
	AND E.SALARY > ALL(SELECT SALARY
					FROM OEHR_EMPLOYEES
					WHERE UPPER(LAST_NAME) = 'TAYLOR');

    
-- QUISIERA SABER APELLIDO Y PAÍS DE TODOS AQUELLOS TRABAJADORES QUE GANEN MÁS QUE
-- EL SUELDO PROMEDIO DE TODOS LOS TRABAJADORES

-- QUISIERA SABER EL NOMBRE DEL DEPARTAMENTO Y EL SUELDO MÍNIMO ASOCIADO POR CADA
-- UNO, SIEMPRE Y CUANDO EL SUELDO MÍNIMO, SEA MAYOR QUE EL SUELDO MÍNIMO DEL 
-- DEPARTAMENTO 80

-- QUISIERA SABER EL COD_EMPLEADO, APELLIDO, NOMBRE_CARGO Y SUELDO DE TODOS AQUELLOS
-- TRABAJADORES QUE SU SUELDO SEA MENOR QUE ALGÚN SUELDO DEL CARGO 'SA_MAN' Y SU 
-- CARGO SEA DISTINTO A 'SA_MAN'

-- QUISIERA SABER EL COD_EMPLEADO, APELLIDO, NOMBRE_CARGO Y SUELDO DE TODOS AQUELLOS
-- TRABAJADORES QUE SU SUELDO SEA MENOR QUE TODOS LOS SUELDOS DEL CARGO 'SA_MAN' Y 
-- SU CARGO SEA DISTINTO A 'SA_MAN