-- QUISIERA SABER EL PROMEDIO DE LOS SUELDOS DE TODOS LOS TRABAJADORES
SELECT ROUND(AVG(SALARY), 0) AS "PROMEDIO_SUELDOS"
FROM OEHR_EMPLOYEES;

-- QUISIERA SABER EL PROMEDIO DE LOS SUELDOS DE LOS TRABAJADORES DEL 
-- DEPARTAMENTO 90

SELECT ROUND(AVG(SALARY), 0) AS "PROMEDIO_SUELDOS"
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID = 90;

-- QUISIERA SABER LA PRIMERA Y LA ÚLTIMA FECHA DE CONTRATACIÓN DE TODOS 
-- LOS EMPLEADOS

SELECT MIN(HIRE_DATE) AS "PRIMERA_FECHA", MAX(HIRE_DATE) AS "ULTIMA_FECHA"
FROM OEHR_EMPLOYEES;


-- QUISIERA SABER LA CANTIDAD DE DEPARTAMENTOS QUE POSEEN POR LO MENOS 
-- UN TRABAJADOR

SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM OEHR_EMPLOYEES;

-- QUISIERA SABER LA CANTIDAD DE TRABAJADORES QUE PERCIBEN RENTAS MAYORES
-- A LOS 10MIL DÓLARES

SELECT COUNT(EMPLOYEE_ID)
FROM OEHR_EMPLOYEES
WHERE SALARY>10000;


-- QUISIERA SABER LA DIFERENCIA DE LOS SUELDOS MÁXIMO Y MÍNIMO

SELECT MAX(SALARY)-MIN(SALARY) AS "DIFERENCIA_SUELDOS"
FROM OEHR_EMPLOYEES;


-- QUISIERA UN REPORTE CON EL PROMEDIO DE LOS SUELDOS DE CADA DEPARTAMENTO, 
-- MOSTRANDO LOS DEPARTAMENTOS CON SU CÓDIGO ASOCIADO: 
-- COD_DEPARTAMENTO, PROM_SUELDOS

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 0)  AS "DIFERENCIA_SUELDOS"
FROM OEHR_EMPLOYEES;

-- NO FUNCIONA, PORQUE EN UNA COLUMNA TENDRÁ MUCHOS DATOS
-- COMO RESULTADO Y EN LA OTRA, SÓLO 1.

-- ESTRUCTURA DE UN SELECT ACTUALIZADA
SELECT QUÉ VOY A MOSTRAR
FROM DE DÓNDE LO VOY A SACAR
WHERE A QUÉ RESTRICCIONES ESTÁ SUJETO EL RESULTADO
GROUP BY BAJO QUÉ CAMPO DEL SELECT ESTOY AGRUPANDO EL RESULTADO
ORDER BY ORDENADO SEGÚN UN CAMPO DE LA CLÁUSULA SELECT

-- RESOLVAMOS EL REQUERIMIENTO ANTERIOR

SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO", ROUND(AVG(SALARY), 0)  AS "PROM_SUELDOS"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- Y SI QUISIERAMOS ORDERNAR LOS SUELDOS PROMEDIO POR DEPARTAMENTO?

SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO", ROUND(AVG(SALARY), 0)  AS "PROM_SUELDOS"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 1;

-- CON LA FINALIDAD DE GENERAR PRESUPUESTOS, QUISIERA MONTAR UN REPORTE QUE SE 
-- ENCARGUE DE SABER CUÁL ES EL TOTAL ACUMULADO DE LOS SUELDOS POR DEPARTAMENTO 
-- Y DE ACUERDO A SU CARGO, ORDENADO POR DEPARTAMENTO: COD_DEPARTAMENTO, CARGO
-- SUMATORIA_SUELDOS, ADEMÁS EL SUELDO BAJO EL SIGUIENTE FORMATO: $XXX,XXX.XX

SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO", JOB_ID AS "CARGO", TO_CHAR(SUM(SALARY), '$999,999.99') AS "SUM_SUELDOS"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID;

-- QUISIERA UN REPORTE DONDE SE BUSQUE EL SUELDO MÁXIMO POR DEPARTAMENTO, SIEMPRE
-- Y CUANDO, ESTE SUELDO MÁXIMO SEA MAYOR QUE, 10000.

SELECT MAX(SALARY) AS "SUELDO_MAXIMO", DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE MAX(SALARY) > 10000
GROUP BY DEPARTMENT_ID;

-- NO APLICA, DEBIDO A QUE WHERE FILTRA TODO, 
-- Y LUEGO SE AGRUPA

-- ESTRUCTURA DE UN SELECT ACTUALIZADA
SELECT QUÉ VOY A MOSTRAR
FROM DE DÓNDE LO VOY A SACAR
WHERE A QUÉ RESTRICCIONES ESTÁ SUJETO EL RESULTADO
GROUP BY BAJO QUÉ CAMPO DEL SELECT ESTOY AGRUPANDO EL RESULTADO
HAVING RESTRICCIONES DE GRUPO A LAS QUE ESTÁ SUJETO EL RESULTADO
ORDER BY ORDENADO SEGÚN UN CAMPO DE LA CLÁUSULA SELECT

-- CÓMO RESOLVER EL REQUERIMIENTO ANTERIOR

SELECT MAX(SALARY) AS "SUELDO_MAXIMO", DEPARTMENT_ID
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000;


-- QUISIERA UN REPORTE DONDE SE BUSQUE EL SUELDO MÁXIMO POR DEPARTAMENTO, SIEMPRE
-- Y CUANDO, ESTE SUELDO MÁXIMO SEA MAYOR QUE 10000, Y LOS DEPARTAMENTOS ESTÉN
-- EN EL RANGO DEL 50 AL 90, ORDENADO POR DEPARTAMENTO DESCENDENTE.

SELECT DEPARTMENT_ID, MAX(SALARY) AS "SUELDO_MAXIMO"
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 90
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000 
ORDER BY DEPARTMENT_ID DESC;


















