SELECT QUÉ QUIERO VER
FROM DE DÓNDE LO VOY A SACAR

-- QUISIERA UN REPORTE QUE VISUALICE EL COD_TRABAJADOR, EL NOMBRE CONCATENADO 
-- CON EL APELLIDO, EL NOMBRE DEL CARGO QUE TIENE, ADEMÁS DEL NOMBRE DEL 
-- DEPARTAMENTO AL QUE PERTENECE

SELECT EMPLOYEE_ID AS "COD_TRABAJADOR", CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", 
    JOB_TITLE AS "CARGO", DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES, OEHR_JOBS, OEHR_DEPARTMENTS;

-- FUNCIONA, PERO LOS DATOS NO SON COHERENTES PORQUE SE GENERA UN PRODUCTO 
-- CARTESIANO AL NO RESPETAR LAS RESTRICCIONES PROPIAS DEL MODELO (FK)

-- AFECTA LA INTEGRIDAD, YA QUE LOS RESULTADOS NO SON CORRECTOS.

-- CÓMO RESOLVEMOS EL REQUERIMIENTO ANTERIOR.

-- ICLUYENDO JOINS EN LA CLAUSULA FROM, CONSIDERANDO GENERAR UNA SOLA TABLA
-- PARA ACARRERAR LOS REGISTROS YA FILTRADOS SEGÚN INDICAN LAS RESTRICCIONES
-- INDICADAS AHÍ.

SELECT EMPLOYEE_ID AS "COD_TRABAJADOR", CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", 
    JOB_TITLE AS "CARGO", DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES JOIN OEHR_JOBS ON(JOB_ID = JOB_ID)
    JOIN OEHR_DEPARTMENTS ON(DEPARTMENT_ID = DEPARTMENT_ID);

-- NO FUNCIONA PORQUE SE PRESENTA AMBIGÜEDAD EN ALGUNOS CAMPOS.

-- ALIAS DE TABLA ME PERMITE LLAMAR A UNA TABLA POR UN NOMBRE MÁS CORTO (VARIABLE)
-- YA QUE CUANDO ME REFIERO A UN CAMPO QUE ESTÁ EN MÁS DE UNA TABLA Y SE ESCRIBE
-- CON EL MISMO NOMBRE, DEBEN LLAMARSE POR NORMA: TABLA.CAMPO, Y POR ELLO, EL ALIAS
-- DE TABLA ME PERMITE LLAMARLO: ALIAS.CAMPO

-- POR NORMA GENERAL, SIN ALIAS DE TABLA

SELECT OEHR_EMPLOYEES.EMPLOYEE_ID AS "COD_TRABAJADOR", CONCAT(OEHR_EMPLOYEES.FIRST_NAME,CONCAT(' ',OEHR_EMPLOYEES.LAST_NAME)) AS "NOMBRE", 
    OEHR_JOBS.JOB_TITLE AS "CARGO", OEHR_DEPARTMENTS.DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES JOIN OEHR_JOBS ON(OEHR_EMPLOYEES.JOB_ID = OEHR_JOBS.JOB_ID)
    JOIN OEHR_DEPARTMENTS ON(OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID);


-- UTILIZANDO ALIAS DE TABLA

SELECT E.EMPLOYEE_ID AS "COD_TRABAJADOR", CONCAT(E.FIRST_NAME,CONCAT(' ',E.LAST_NAME)) AS "NOMBRE", 
    J.JOB_TITLE AS "CARGO", D.DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON(E.JOB_ID = J.JOB_ID)
    JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID);

-- QUISIERA UN REPORTE QUE INDIQUE LO SIGUIENTE: COD_EMPLEADO, APELLIDO_EMPLEADO, 
-- NOMBRE_CONTINENTE EN EL QUE VIVE

-- ESTRUCTURA PARA CONSULTAS MULTITABLA
SELECT QUÉ QUIERO MOSTRAR
FROM DE QUÉ TABLA LO VOY A SACAR JOIN CON QUÉ TABLA LO VOY A INTERSECTAR ON(PUNTO DE INTERSECCIÓN)


-- CÓMO RESUELVO EL REQUERIMIENTO ANTERIOR UTILIZANDO JOINS?

SELECT E.EMPLOYEE_ID, E.LAST_NAME, R.REGION_NAME
FROM OEHR_EMPLOYEES E JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
    JOIN OEHR_LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
    JOIN OEHR_COUNTRIES CO ON(L.COUNTRY_ID = CO.COUNTRY_ID)
    JOIN OEHR_REGIONS R ON(CO.REGION_ID = R.REGION_ID);


-- QUISIERA VER EL COD_EMPLEADO, CONCATENADO EL COD_CARGO CON EL APELLIDO DEL 
-- TRABAJADOR DE LA SIGUIENTE FORMA: CASTRO ES ACA_UCM, 
-- ADEMÁS DEL NOMBRE DEL CARGO QUE TIENE. ENTIÉNDASE QUE LAS BARRAS SON
-- SEPARADORES VISUALES, NO DEBEN ESTAR CONCATENADAS. =)

-- COD       DATO CONCATENADO         CARGO
-- _____________________________________________
-- 101   |   CASTRO ES ACA_UCM   |   ACADÉMICO


SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO", UPPER(CONCAT(E.LAST_NAME,CONCAT(' ES ',CONCAT(J.JOB_ID,'_UCM')))) AS "REPORTE", J.JOB_TITLE "CARGO"
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON(E.JOB_ID = J.JOB_ID);


----------------------------TAREA------------------------------------------------
-- QUISIERA SABER COD_TRABAJADOR, APELLIDO DE TRABAJADOR, NOMBRE DEL DEPARTAMENTO ASOCIADO,
-- Y EN CASO DE NO ESTAR ASOCIADO A UN DEPARTAMENTO, EL TRABAJADOR DEBE MOSTRARSE IGUAL.


-- QUISIERA SABER DEL TRABAJADOR: NOMBRE CONCATENADO CON EL APELLIDO, SU CÓDIGO, 
-- EL NOMBRE DE SU DEPARTAMENTO ASOCIADO Y EL NOMBRE DEL JEFE ASOCIADO A DICHO
-- DEPARTAMENTO ADEMÁS DE LA CIUDAD EN LA QUE SE ENCUENTRA Y ADEMÁS DEL NOMBRE 
-- DE SU CARGO.

