-- QUISIERA QUE PROBARAN LAS FUNCIONES ROUND, TRUNC Y MOD, SIN EMBARGO, NO QUIERO
-- QUE CONSULTEN UNA TABLA, PARA ELLO EN LA CLÁUSULA FROM SE DEBE INCLUIR LA TABLA
-- VIRTUAL DUAL, PARA ROUND PROBAR 45.5674 MOSTRANDO 3, 2, 1 Y 0 DECIMALES, LO MISMO
-- PARA LA FUNCIÓN TRUNC, SIN EMBARGO PARA EL MOD, ESTO TIENE QUE TRABAJARSE CON
-- LA DIVISIÓN ENTRE 54 ENTRE 3.
SELECT ROUND(45,5674,3), ROUND(45,5674,2), ROUND(45,5674,1), ROUND(45,5674,0)
FROM DUAL;

SELECT TRUNC(45,5674,3), TRUNC(45,5674,2), TRUNC(45,5674,1), TRUNC(45,5674,0)
FROM DUAL;

SELECT MOD(54/3)
FROM DUAL;

--------------------------- TAREA ------------------------------------------------
-- QUISIERA SABER CUANTO LLEVA TRABAJANDO CADA EMPLEADO, EN SEMANAS. 
-- DE ACUERDO A LO SIGUIENTE: COD_EMPLEADO, NOMBRE CONCATENADO CON EL 
-- APELLIDO, FECHA_CONTRATO, SEMANAS_TRABAJADAS. SIEMPRE Y CUANDO PERTENEZCAN
-- AL DEPARTAMENTO 50 O AL 80, ORDENADOS DEL QUE MENOS HA TRABAJADO, AL QUE
-- MÁS HA TRABAJADO.

SELECT SYSDATE
FROM DUAL;



SELECT EMPLOYEE_ID AS "COD_EMPLEADO", UPPER(CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME))) AS "NOMBRE", HIRE_DATE AS "FECHA_CONTRATO", TRUNC((SYSDATE-HIRE_DATE)/7,0) AS "SEMAMAS_TRABAJADAS"
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IN (50,80)
ORDER BY 4;
--ORDER BY 4 SE REFIERE A LA 4TA COLUMNA DESCRITA EN EL CODIGO "SELECT"

---- CREAR ESTA TABLA CON SUS PREFIJOS CORRESPONDIENTES A SUS INICIALES
CREATE TABLE CACB_EJEMPLO(
	RUT VARCHAR2(12)
);

-- LA SIGUIENTE INSTRUCCIÓN APLICA CORRECTAMENTE YA QUE SE INGRESÓ COMO SE SOLICITA
INSERT INTO EJEMPLO (RUT)
	VALUES('13.572.343-2');

-- LA SIGUIENTE INSTRUCCIÓN NO SE PUEDE CONVERTIR DE FORMA IMPLÍCITA, YA QUE EL NÚMERO
-- COMO NÚMERO PRIMERO NO EXISTE Y LUEGO NO SE PUEDE HACER LA RESTA CORRESPONDIENTE
INSERT INTO EJEMPLO (RUT) 
	VALUES(13.572.343-2);

