-- NVL(valor_a_evaluar, valor_de_retorno)

-- valor_a_evaluar = eventalmente es una variable, que puede tener valores "nulos"
-- valor_de_retorno = es aquel valor, que en caso de que el valor_a_evaluar sea null,
--	se retornará valor_de_retorno

-- SÓLO EN CASO DE ENCONTRAR UN NULO, CASO CONTRARIO, SE MANTIENE EL MISMO VALOR

-- AMBOS ARGUMENTOS DE LA FUNCIÓN DEBEN SER DEL MISMO TIPO DE DATOS.
-- EJEMPLO: NVL(VARIABLE, 5) // DONDE VARIABLE ES DE TIPO NUMÉRICO Y ALVERGA LOS VALORES 
-- NULL,10, 20
-- CUÁL SERÁ EL RETORNO DE LA FUNCIÓN? 5, 10, 20


-- QUISIERA UN REPORTE CONSTRUIDO DE LA SIGUIENTE FORMA:
-- COD_TRABAJADOR, APELLIDO, SUELDO ($25,000.00), COMISIÓN ASOCIADA (MOSTRADA 
-- CON VALORES NUMÉRICOS PARA TODOS LOS TRABAJADORES: 100.00%) Y SU COMISIÓN ASOCIADA
-- EN TÉRMINO DE DÓLARES GANADOS POR CONCEPTO DE COMISIÓN ($100.00), PARA TODOS LOS 
-- TRABAJADORES

SELECT EMPLOYEE_ID, LAST_NAME, TO_CHAR(SALARY,'$999,999.99') AS "SALARY", 
	CONCAT(TO_CHAR(NVL(COMMISSION_PCT,0)*100,'999.99'),'%') AS "COMMISSION_PCT", 
	TO_CHAR(SALARY*NVL(COMMISSION_PCT,0),'$999,999.99') AS "SUELDO_POR_COMISION"
FROM OEHR_EMPLOYEES;

TO_CHAR(DATE, 'FM')		-> CADENA
TO_CHAR(NUMBER, 'FM') 	-> CADENA


-------------------------------------------------------------------------------
----------------------------TAREA------------------------------------------------
---------------------------------------------------------------------------------

-- QUISIERA UN REPORTE CONSTRUIDO DE LA SIGUIENTE FORMA:
-- COD_TRABAJADOR, APELLIDO, SUELDO ($25,000.00), COMISIÓN ASOCIADA (MOSTRADA 
-- CON VALORES NUMÉRICOS PARA TODOS LOS TRABAJADORES: 100) Y EN CASO
-- DE QUE NO TENGA COMISIÓN, ESCRIBA EL TEXTO: 'SIN COMISIÓN'

SELECT EMPLOYEE_ID, LAST_NAME, TO_CHAR(SALARY,'$999,999.99') AS "SALARY", 
	NVL2(COMMISSION_PCT, TO_CHAR(COMMISSION_PCT*100,'999'),'SIN COMISION') AS "COMMISSION_PCT"
FROM OEHR_EMPLOYEES;

--NVL2(ARG1, ARG2, ARG3)


-- SI EL ARG1 NO ES NULO, EL VALOR DE RETORNO SERÁ ARG2, POR OTRO LADO,
-- SI EL ARG1 ES NULO EL VALOR DE RETORNO SERÁ ARG3

-- NVL2(NULL,'TEXTO1','TEXTO2') -> TEXTO2 

-- NVL2('CARLOS','CASTRO','BUSTAMANTE') -> CASTRO


-- DA LO MISMO LA VARIABLE QUE SE EVALUE EN TÉRMINOS DE TIPO SIN EMBARGO, ARG2 Y ARG3 DEBEN
-- SER DEL MISMO TIPO

-- RECORDAR QUE EL RESTO LAS FUNCIONES APLICAN DE LA MISMA FORMA Y EJEMPLOS 
-- TENEMOS EN EL MATERIAL PPT

