-- U1_L2

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO
-- DE TODOS LOS EMPLEADOS.
   
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES;

-- PARA TRABAJAR RESTRICCIÓN DE DATOS SE INCLUYE UNA 3RA CLÁUSULA
-- QUE PERMITE HACER ESTO, MEDIANTE CONDICIONES: WHERE(CONDICION)
SELECT QUÉ QUIERO VER
FROM DE DÓNDE LO VOY A SACAR
WHERE Y A QUÉ RESTRICCIONES ESTÁ SUJETO EL RESULTADO

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO
-- DE TODOS AQUELLOS EMPLEADOS DEL DEPARTAMENTO 90.
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID = 90;

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO, DEPARTAMENTO Y FECHA DE
-- CONTRATACIÓN DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUÉS
-- DEL AÑO 2015
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE > '12/31/2015');

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE >= '01/01/2016');

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO
-- DE LA EMPLEADA WHALEN.

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE LAST_NAME = 'Whalen';

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE FIRST_NAME = 'Whalen' OR LAST_NAME = 'Whalen';

-- CUANDO NO HAY CLARIDAD, ASOCIADO A SI WHALEN ES NOMBRE O APELLIDO,
-- DEBO GENERAR UNA DOBLE RESTRICCIÓN UNIDAS CON UN OPERADOR LÓGICO.
-- EN SQL SE TRABAJAN CON SUS EXPRESIONES LITERALES: AND OR NOT 

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO 
-- DE TODOS AQUELLOS EMPLEADOS QUE GANEN ENTRE 3000 Y 5000 USD

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID ,SALARY
FROM OEHR_EMPLOYEES
WHERE SALARY >= 3000 and SALARY <= 5000;

-- EL OPERADOR BETWEEN ME PERMITE FILTRAR DATOS DE ACUERDO A UN RANGO
-- VALORES, PENSANDO EN LÍMITE INFERIOR Y UN LÍMITE SUPERIOR 
-- CORRESPONDIENTEMENTE, QUEDANDO COMO CONDICIÓN
-- WHERE( CAMPO_RESTRINGIDO BETWEEN LIM_INF AND LIM_SUP )

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID ,SALARY
FROM OEHR_EMPLOYEES
WHERE(SALARY BETWEEN 3000 AND 5000);

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO 
-- DE TODOS AQUELLOS EMPLEADOS QUE NO HAYAN SIDO CONTRATADOS ENTRE
-- LOS AÑOS 2015 Y 2020

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE HIRE_DATE NOT BETWEEN '01/01/2015' AND '12/31/2020';


-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO 
-- DE TODOS AQUELLOS EMPLEADOS QUE TRABAJEN EN LOS DEPARTAMENTOS
-- 90, 100 Y 50

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID=90 OR DEPARTMENT_ID=100 OR DEPARTMENT_ID =50;

-- EL OPERADOR IN ME PERMITE TRABAJAR EN LA RESTRICCIÓN DE UN CAMPO, 
-- CONSIDERANDO UN CONJUNTO DE VALORES, QUE SE DISTRIBUYE CON EL OPERADOR
-- LÓGICO OR DE LA SIGUIENTE FORMA
-- WHERE CAMPO_RESTRINGIDO IN (VALORES SEPARADOS POR COMA)

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IN(90,100,50);


-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO 
-- DE TODOS AQUELLOS EMPLEADOS, DONDE SUS JEFES NO SEAN LOS QUE ESTÁN
-- CODIFICADOS CON LOS SIGUIENTES NÚMEROS: 100, 120, 114 Y 121

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE MANAGER_ID<>100 OR MANAGER_ID<>120 OR  MANAGER_ID<>114 OR MANAGER_ID<> 121;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE MANAGER_ID NOT IN(100,120,114,121);


-- QUISIERA VER LOS DATOS DE TODOS AQUELLOS TRABAJADORES EN LOS QUE SU 
-- APELLIDO COMIENCE CON LA LETRA S O TERMINE CON LA LETRA A
SELECT *
FROM OEHR_EMPLOYEES
WHERE LAST_NAME = 'S------'?

-- CON MÉTODOS CONVENCIONALES, NO HAY CÓMO RESOLVERLO =)


-- PARA RESOLVER EL REQUERIMIENTO ANTERIOR, ES NECESARIO TRABAJAR CON EL
-- OPERADOR LIKE, QUE TRABAJA DE LA SIGUIENTE FORMA:
-- WHERE CAMPO_RESTRINGIDO LIKE 'TEXTO_DEFINIDO'

-- CONSIDERANDO QUE EN 'TEXTO DEFINIDO', DEBO INDICAR UN PATRÓN DE COMPOR-
-- TAMIENTO CON LOS COMODINES _ Y %

-- EL % SE UTILIZA PARA DECIR "NO ME INTERESA LO QUE HAYA EN UNA PARTE
-- COMPLETA DE LA CADENA"

-- EL _ SE UTILIZA PARA DECIR "NO ME INTERESA LO QUE HAYA EN UN CARACTER
-- PARTICULAR DE LA CADENA"

-- DADO LO ANTERIOR, CÓMO SE RESUELVE EL REQUERIMIENTO ANTERIOR?
SELECT *
FROM OEHR_EMPLOYEES
WHERE LAST_NAME LIKE 'S%' OR LAST_NAME LIKE '%a';


-- SI LA RESTRICCIÓN FUERA INCLUYENTE, BASTARÍA SÓLO CON UNA CONDICIÓN

SELECT *
FROM OEHR_EMPLOYEES
WHERE LAST_NAME LIKE 'S%a';

-- TAREA1
-- QUISIERA VER LOS DATOS DE TODOS AQUELLOS DEPARTAMENTOS EN LOS QUE SU 
-- NOMBRE TENGA COMO SEGUNDA LETRA LA A Y TERMINE CON LA LETRA S


-- TAREA2
-- QUISIERA VER COD, NOMBRE Y APELLIDO CONCATENADOS, DE TODOS AQUELLOS
-- TRABAJADORES, DONDE SU CARGO TENGA COMO PENÚLTIMA LETRA LA A


-- TAREA3
-- QUISIERA VER COD, NOMBRE Y APELLIDO CONCATENADOS, DE TODOS AQUELLOS
-- TRABAJADORES, DONDE SU APELLIDO NO TENGA CONTENIDA LA LETRA A


-- QUISIERA VER LOS DATOS DE TODOS AQUELLOS TRABAJADORES QUE NO ESTÉN
-- SUJETOS A COMISIÓN.
SELECT * 
FROM OEHR_EMPLOYEES
WHERE COMMISSION_PCT = NULL;

-- PRESENTA INCOSNSITENCIA, POR LO QUE NO
							 -- APLICA

-- PARA REALIZAR COMPARACIONES CON CAMPOS QUE EVENTUALMENTE PUEDAN TENER
-- "VALORES" NULOS, SE UTILIZA LA FUNCIÓN DE COMPARACIÓN "IS NULL" O SU
-- NEGADA "IS NOT NULL"

SELECT * 
FROM OEHR_EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- POR ÚLTIMO, SI YO QUISIERA ORDENAR LOS DATOS, APARECE UNA NUEVA CLÁUSULA
-- DEFINIDA COMO "ORDER BY" LA CUAL VA ACOMPAÑADA DE UNO O MÁS CAMPOS
-- DEFINIDOS EN LA CLÁUSULA SELECT, DE ACUERDO AL NIVEL DE ORDENAMIENTO 
-- QUE REQUIERA HACER, PUDIENDO UTILIZAR ALIAS DE COLUMNA Y NÚMEROS, DE
-- ACUERDO A LA POSICIÓN DEL CAMPO EN LA CLÁUSULA SELECT 

SELECT QUÉ QUIERO VER
FROM DE DÓNDE LO VOY A SACAR
WHERE BAJO QUE RESTRICCIONES SE ENCUENTRA EL RESULTADO
ORDER BY CÓMO VOY A ORDENAR EL RESULTADO FINAL

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO, DEPARTAMENTO Y FECHA DE
-- CONTRATACIÓN DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUÉS
-- DEL AÑO 2015, ORDENADO POR APELLIDO

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE > '12/31/2015')
ORDER BY LAST_NAME;


-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO, DEPARTAMENTO Y FECHA DE
-- CONTRATACIÓN DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUÉS
-- DEL AÑO 2015, ORDENADO POR FECHA DE CONTRATACIÓN DE MANERA DESCENDENTE

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE > '12/31/2015')
ORDER BY HIRE_DATE;

-- NO APLICA, PORQUE EL ORDEN POR DEFECTO ES ASCENDENTE


-- PARA ORDEN ASCENDENTE, SE TRABAJA SÓLO INCLUYENDO EL NOMBRE DEL CAMPO
-- YA QUE ES UN RESULTADO POR DEFECTO, SIN EMBARGO, SI QUIERO HACERLO
-- EXPLÍCITO, DEBO ESCRIBIR A CONTINUACIÓN DEL CAMPO LA PALABRA RESERVADA
-- "ASC" Y EN CASO CONTRARIO SI QUIERO QUE SEA DESCENDENTE, ESTOY EN LA
-- OBLIGACIÓN DE QUE A CONTINUACIÓN DEL CAMPO DEBO ESCRIBIR LA PALABRA 
-- "DESC"

-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO, DEPARTAMENTO Y FECHA DE
-- CONTRATACIÓN DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUÉS
-- DEL AÑO 2015, ORDENADO POR FECHA DE CONTRATACIÓN DE MANERA DESCENDENTE

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE > '12/31/2015')
ORDER BY HIRE_DATE DESC;


-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO, DEPARTAMENTO Y FECHA DE
-- CONTRATACIÓN DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUÉS
-- DEL AÑO 2015, ORDENADO POR DEPARTAMENTO Y LUEGO POR FECHA DE 
-- CONTRATACIÓN, LA ÚLTIMA DE MANERA DESCENDENTE, PARA TERMINAR POR APELLIDO

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE (HIRE_DATE > '12/31/2015')
ORDER BY DEPARTMENT_ID, HIRE_DATE DESC;
