-- QUISIERA VER COD_EMPLEADO, NOMBRE Y APELLIDO CONCATENADOS, Y CORREO DE 
-- TODOS LOS TRABAJADORES, TODO EN MAYÚSCULA

SELECT EMPLOYEE_ID, UPPER(FIRST_NAME||' '||LAST_NAME) AS "NOMBRE", UPPER(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;

-- QUISIERA VER COD_EMPLEADO, NOMBRE Y APELLIDO CONCATENADOS, Y CORREO DE 
-- TODOS LOS TRABAJADORES, TODO EN MINÚSCULA

SELECT EMPLOYEE_ID, LOWER(FIRST_NAME||' '||LAST_NAME) AS "NOMBRE", LOWER(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;

-- QUISIERA VER COD_EMPLEADO, NOMBRE Y APELLIDO CONCATENADOS, Y CORREO DE 
-- TODOS LOS TRABAJADORES, TODO CON SU PRIMERA LETRA EN MAYÚSCULA

SELECT EMPLOYEE_ID, INITCAP(FIRST_NAME||' '||LAST_NAME) AS "NOMBRE", INITCAP(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;


-- QUISIERA MOSTRAR COD_EMPLEADO, APELLIDO, CARGO Y DEPARTAMENTO
-- DE LA EMPLEADA WHALEN, CONSIDERANDO LA RESTRICCIÓN TAL Y COMO ESTÁ
-- ESCRITA EN ESTE REQUERIMIENTO.

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE UPPER(LAST_NAME) = 'WHALEN';


-- QUISIERA VER COD_EMPLEADO, NOMBRE Y APELLIDO CONCATENADOS, Y CORREO DE 
-- TODOS LOS TRABAJADORES, TODO EN MAYÚSCULA, UTILIZANDO LA FUNCIÓN CONCATENAR

CONCAT(PARAM1, PARAM2) -> RESULTADO CORREPONDIENTE A PARAM1 Y PARAM2 CONCATENADOS

SELECT EMPLOYEE_ID, UPPER(CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME))) AS "NOMBRE", EMAIL
FROM OEHR_EMPLOYEES;


--QUISIERA QUE CORTARAN LA PENÚLTIMA LETRA DE CADA CORREO ELECTRÓNICO
--ESTO APLICA PARA CADA EMPLEADO Y LUEGO DEBEN CONCATENARLO CON @SQL.CL

EMAIL
JWHALEN -> JWHALN

JWHALEN

JWHAL
N

JWHALN

JWHALN@SQL.CL

SELECT CONCAT(SUBSTR(EMAIL,1,LENGTH(EMAIL)-2),CONCAT(SUBSTR(EMAIL,LENGTH(EMAIL)),'@SQL.CL')) AS "EMAIL"
FROM OEHR_EMPLOYEES;


-- QUISIERA QUE MONTARAN UN CORREO ELECTRÓNICO PARA CADA TRABAJADOR QUE
-- MANTENGA EL SIGUIENTE PATRÓN: PRIMERA LETRA DEL NOMBRE, CONCATENADO
-- CON EL APELLIDO Y TODO LO ANTERIOR CONCATENADO CON @SQL.CL

Carlos Castro -> CCASTRO -> CCASTRO@SQL.CL


SELECT UPPER(CONCAT(SUBSTR(FIRST_NAME,1,1),CONCAT(LAST_NAME,'@SQL.CL'))) AS "EMAIL"
FROM OEHR_EMPLOYEES;

