-- QUISIERA TRANSFORMAR LA FECHA DE HOY DESDE LOS NÚMEROS DEL FORMATO POR DEFECTO
-- A UN TEXTO QUE DIGA DÍA MES AÑO (MIÉRCOLES 21 DE AGOSTO DE DOS MIL VEINTICUATRO)

SELECT SYSDATE
FROM DUAL;

TO_CHAR(DATE, 'FM')


SELECT TO_CHAR(SYSDATE,'DAY DD "TH" MONTH "OF" YEAR') AS "SYSDATE"
FROM DUAL;


-- QUISIERA VER LOS SIGUIENTES DATOS DE LOS TRABAJADORES:
-- COD_EMPLEADO, NOMBRE CONCATENADO CON SU APELLIDO, EMAIL CONCATENADO CON 
-- @BD.UCM.CL Y SU FECHA DE CONTRATACIÓN BAJO EL SIGUIENTE FORMATO: 
-- 31 DE AGOSTO DE 2022

SELECT EMPLOYEE_ID AS "COD_EMPLEADO", CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", CONCAT(EMAIL,'@BD.UCM.CL') AS "EMAIL", TO_CHAR(HIRE_DATE, 'DD "TH" MONTH "OF" YYYY')
FROM OEHR_EMPLOYEES;


-- QUISIERA VER LOS SIGUIENTES DATOS DE LOS TRABAJADORES:
-- COD_EMPLEADO, NOMBRE CONCATENADO CON SU APELLIDO, EMAIL CONCATENADO CON @BD.UCM.CL
-- Y SU SUELDO BAJO EL SIGUIENTE FORMATO: $24,000.00

SELECT EMPLOYEE_ID AS "COD_EMPLEADO", CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", CONCAT(EMAIL,'@BD.UCM.CL') AS "EMAIL", TO_CHAR(SALARY,'$99,999.99')
FROM OEHR_EMPLOYEES;



-- QUISIERA QUE DESCOMPONGA LA FECHA ACTUAL Y SÓLO MUESTRE EL AÑO

-- 21-08-2024
-- 2024

SELECT TO_CHAR(SYSDATE,'YYYY') AS "SYSDATE"
FROM DUAL;

-- QUISIERA QUE EL AÑO IDENTIFICADO EN EL REQUERIMIENTO ANTERIOR, LO TRANSFORME
-- EN NÚMERO

SELECT TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'),'9999') AS "SYSDATE"
FROM DUAL;


-- QUISIERA QUE LO TRABAJADO EN LOS REQUERIMIENTOS ANTERIORES, SE UTILICE PARA 
-- RESOLVER LO SIGUIENTE: QUSIERA VER EL CÓDIGO, NOMBRE Y APELLIDO, ADEMÁS DE 
-- LA FECHA DE CONTRATACIÓN DE TODOS AQUELLOS TRABAJADORES QUE FUERON CONTRATADOS
-- POSTERIOR AL AÑO 1995 (SIENDO ESTA RESTRICCIÓN LITERAL SÓLO INCLUYENDO EL AÑO DE
-- LA FECHA), Y QUE SEAN ORDENADOS POR FECHA DE CONTRATACIÓN DE MAYOR A MENOR.

SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYY'),'9999') > 1995
ORDER BY HIRE_DATE DESC;

-- QUISIERA QUE LO TRABAJADO EN LOS REQUERIMIENTOS ANTERIORES, SE UTILICE PARA 
-- RESOLVER LO SIGUIENTE: QUSIERA VER EL CÓDIGO, NOMBRE Y APELLIDO, ADEMÁS DEL 
-- AÑO DE CONTRATACIÓN ESCRITO DE FORMA NUMÉRICA Y CON CUATRO DÍGITOS DE TODOS
-- AQUELLOS TRABAJADORES QUE FUERON CONTRATADOS POSTERIOR AL AÑO 1995 (SIENDO 
-- ESTA RESTRICCIÓN LITERAL SÓLO INCLUYENDO EL AÑO DE LA FECHA), Y QUE SEAN 
-- ORDENADOS POR AÑO DE MAYOR A MENOR.

SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS "NOMBRE", TO_CHAR(HIRE_DATE,'YYYY') AS "ANIO_CONTRATACION"
FROM OEHR_EMPLOYEES
WHERE TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYY'),'9999') > 1995
ORDER BY ANIO_CONTRATACION DESC;
