--consultas multitabla

SELECT QUE QUIERO VER
FROM DE DONDE LO VOY A SACAR

--QUISIERA UN REPORTE QUE VISUALIZE EL COD_TRABAJADOR, EL NOMBRE CONCATENADO
--CONE LE APELLIDO, EL NOMBRE DEL CARGO Q TIENE, ADEMAS DEL NOMBRE DEL
--DEPARTAMENTO AL Q PERTENECE

SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
FROM OEHR_EMPLOYEES, OEHR_JOBS, OEHR_DEPARTMENTS;

--FUNCIONA, PERO LOS DATOS NO SON COHERENTES PORQUE SE GENERA UN PRODUCTO
--CARTESIANO AL NO RESPETAR LAS RESTRICCIONES PROPIASDEL MODELO (FK)

--AFECTA LA INTEGRIDAD, YA QUE LOS RESULTADOS NO SON CORRECTOS.

--COMO RESOLVEMOS EL REQUERIMIENTO ANTERIOR.

--INCLUYENDO JOINS EN LA CLAUSULA FROM, CONSIDERANDO GENERAR UNA SOLA TABLA
--PARA ACARREAR LOS REGISTROS YA FILTRADOS SEGUN INDICAN LA RESTRICCIONES
--DADAS AHI.

SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)), JOB_TITLE ,DEPARTMENT_NAME
FROM OEHR_EMPLOYEES JOIN OEHR_JOBS ON(JOB_ID = JOB_ID)
    JOIN OEHR_DEPARTMENTS ON(DEPARTMENT_ID = DEPARTMENT_ID);

--NO FUNCIONA PORQUE SE PRESENTA AMBIGUEDAD EN ALGUNSO CAMPOS.

--ALIAS DE TABLA ME PERMITE