-- Clase 1 --
-- Una consulta básica está dada por las cláusulas select y from
-- considerando la siguiente estructura:
SELECT ESCRIBIR CAMPOS SEPARADOS POR COMA, PARA MOSTRAR DATOS
FROM ESCRIBIR EL NOMBRE DE LA TABLA QUE VA A EXTRAER LOS DATOS

-- SI QUIERE MOSTRAR TODOS LOS CAMPOS DE UNA TABLA, PUEDE REEMPLAZAR
-- LOS NOMBRES DE LOS CAMPOS POR EL COMODÍN *.

-- QUISIERA VER TODOS LOS DATOS DE LOS  DEPARTAMENTOS

SELECT *
FROM OEHR_DEPARTMENTS;

-- QUISIERA VER EL CÓDIGO DEL DEPARTAMENTO Y 
-- SU NOMBRE ASOCIADO

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM OEHR_DEPARTMENTS;

-- PARA SABER LA ESTRUCTURA DE UNA TABLA, PUEDO UTILIZAR EL COMANDO
-- DESCRIBE, ACOMPAÑADO DEL NOMBRE DE LA TABLA QUE QUIERE REVISAR.

DESCRIBE NOMBRE_TABLA;

-- QUISIERA SABER CÓMO ESTÁ DEFINIDA LA TABLA LOCATIONS

DESCRIBE OEHR_LOCATIONS;


-- QUISIERA VER CÓDIGO Y  NOMBRE DE LOS TRABAJADORES, ACOMPAÑADO DE SU
-- SUELDO, ADEMÁS DE UNA SIMULACIÓN DE SU SUELDO, CON UN BONO DE USD100


-- SELECT EMPLOYEE_ID , FIRST_NAME,SALARY, 
-- FROM OEHR_EMPLOYEES


--- PUEDO YO OCUPAR OPERADORES ARITMETICOS (+,-,*,/) DENTRO DE LA CLAUSULA SELECT?
--- SI, CONSIDERANDO LO SIGUIENTE:

SELECT EMPLOYEE_ID , FIRST_NAME,SALARY, SALARY+100
FROM OEHR_EMPLOYEES;


-- QUISIERA VER CÓDIGO Y NOMBRE DE LOS EMPLEADOS, ACOMPAÑADO DE SU
-- SUELDO ANUAL, MÁS UNA SIMULACIÓN DE SU SUELDO ANUAL, CONSIDERANDO UN
-- BONO MENSUAL DE USD57

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY*12, (SALARY+57)*12
FROM OEHR_EMPLOYEES;


-- QUISIERA VER CÓDIGO Y NOMBRE DE LOS EMPLEADOS, ACOMPAÑADO DE SU
-- SUELDO ANUAL, MÁS UNA SIMULACIÓN DE SU SUELDO ANUAL, CONSIDERANDO UN
-- BONO ANUAL DE USD57

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY*12, (SALARY*12)+57
FROM OEHR_EMPLOYEES;


-- QUISIERA VER CÓDIGO Y NOMBRE DE LOS EMPLEADOS, ACOMPAÑADO DE SU 
-- SUELDO ANUAL Y LA CANTIDAD DE USD ANUALES, PERCIBIDOS POR CONCEPTO
-- DE COMISIÓN.

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY*12, SALARY*12*COMMISSION_PCT
FROM OEHR_EMPLOYEES;


-- PARA EL REQUERIMIENTO ANTERIOR, SE NECESITA VISUALIZAR LOS ENCABEZADOS
-- DE CADA CAMPO, CON LOS SIGUIENTES NOMBRES: 
-- 		COD_EMPLEADO, NOMBRE, SUELDO_ANUAL, COMISION_ANUAL

SELECT EMPLOYEE_ID AS "COD_EMPLEADO", FIRST_NAME AS "NOMBRE", SALARY*12 AS "SUELDO_ANUAL", SALARY*12*COMMISSION_PCT AS "COMISION_ANUAL"
FROM OEHR_EMPLOYEES;


-- QUISIERA VER EL CODIGO DE TODOS LOS EMPLEADOS ADEMÁS DE SU NOMBRE 
-- CONCATENADO CON EL APELLIDO.

SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME
FROM OEHR_EMPLOYEES;


-- DE TODOS LOS EMPLEADOS QUISIERA VER EL SIGUIENTE REPORTE:
-- EJEMPLO: EL EMPLEADO JUAN PEREZ TIENE COMO CARGO: PROGRAMADOR

SELECT 'EL EMPLEADO '||FIRST_NAME||' '||LAST_NAME||' TIENE COMO CARGO: '||JOB_ID AS "REPORTE"
FROM OEHR_EMPLOYEES;

-- QUISIERA VER TODOS LOS CARGOS DE LA EMPRESA, CONSIDERANDO EXTRAER LOS
-- DATOS DE LA TRABLA TRABAJADORES.

-- POR NATURALEZA, DEBERÍA EXTRAERSE LA DATA, DE LA TABLA JOBS, SIN EMBARGO
-- EL REQUERIMIENTO OBLIGA A TRABAJAR CON LA TABLA EMPLOYEES, POR ELLO
-- DEBE UTILIZARSE LA PALABRA CLAVE DISTINCT ANTES DEL CAMPO INDICADO.

SELECT DISTINCT JOB_ID
FROM OEHR_EMPLOYEES;
