--QUISIERA SABER EL PROMEDIO DE LOS SUELDOS DE TODOS LOS TRABAJADORES
SELECT ROUND (AVG(SALARY),0) AS "SUELDO_PROMEDIO"
FROM OEHR_EMPLOYEES;

--QUISIERA SABER EL PROMEDIO DE LOS SUELDOS DE LOS TRABAJADORES DEL
--DEPARTAMENTO 90
SELECT ROUND(AVG(SALARY),0) AS "SUELDO_PROMEDIO"
FROM OEHR_E,PLOYEES
WHERE DEPARTMENT_ID = 90;

--QUISIERA SABER LA PRIMERA Y ULTIMA DECHA DE CONTRATACION DE TODOS
--LOS EMPLEADOS
SELECT MIN(HIRE_DATE) AS "PRIMERA FECHA ", MAX(HIRE_DATE) AS "ULTIMA_FECHA"
FROM OEHR_EMPLOYEES;

--QUISIERA SABER LA CANTIDAD DE DEPARTAMENTO Q POSEEN POR LO MENOS
--UN TRABAJADOR
SELECT COUNT (DISTINCT NVL(DEPARTMENT_ID,0))
FROM OEHR_EMPLOYEES;

--QUISIERA SABER LA CANTIDAD DE TRABAJADORES DQUE PERCIBEN RENTAS MAYORES
--A LOS 10MIL DOLARES

SELECT COUNT (EMPLOYEES_ID)
FROM OEHR_EMPLOYEES
WHERE SALARY > 10000;

--QUISIERA SABER LA DIFERENCIA ENTRE LOS SUELDOS MINIMOS Y MAXIMOS

SELECT MAX(SALARY)- MIN(SALARY) AS "DIFERENCIA_SUELDOS"
FROM OEHR_EMPLOYEES;

--QUISIERA UN REPORTE CON EL PROMEDIODELOS SUELDOSDE CADA DEPARTAMENTO,
--MOSTRANDO LOS DEPARTAMENTOS CON SU CODIGO ASOCIADO
--COD_DEPARTAMENTO,PROM_SUELDO

SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO" , ROUND(AVG(SALARY),0) "PROM_SUELDOS"
FROM OEHR_EMPLOYEES;

--NO FUNCIONA , POR QUE EN UNA COLUMNA TENDRA MUCHOS DATOS
--COMO RESULTADO Y EN LA OTRA SOLO 1

--ESTRUCTURA DE UN SELECT ACTUALIZADA
SELECT QUE VOY A MOSTRAR
FROM DE DONDE LO VOY A SACAR
WHERE A QUE RESTICCIONES ESTA SUJETO EL RESULTADO
GROUP BY BAJO QUE CAMPO DEL SELECT ESTOY AGRUPANDO EL RESULTADO
ORDER BY ORDENADO SEGUN UN CAMPO DE LA CLAUSULA SELECT

--RESOLVAMOS EL REQUERIMIENTO ANTERIOR
SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO " , ROUND (AVG(SALARY),0) AS "PROM_SUELDO"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID;

--Y SI QUISIERAMOS ORDENAR LOS SUELDOS PROMEDIO POR DEPARTAMENTO
SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO" , ROUND(AVG(SALARY),0) AS "PROM_SUELDO"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 1;

--CON LA FINALIDAD DE GENERAR PRESUPUESTOS ,QUISIERA MONTAR UN REPORTE QUE SE
--ENCARGUE DE SABER CUAL ES EL TOTAL ACUMULADO DE LOS SUELDOS POR DEPARTAMENTO
--Y DE ACUERDO A SU CARGO, ORDENADO POR DEPARTAMENTO: COD_DEPARTAMENTO, CARGO
--SUMATORIA_SUELDO , ADEMAS EL SUELDO BAJO ELSIGUIENTE FORMATO: $XXX,XXX.XX

SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO", JOB_ID AS "CARGO" ,TO_CHAR (SUM(SALARY), '$999,999.99') AS "SUMATORIA_SUELDO"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID,JOB_ID
ORDER BY DEPARTMENT_ID

--QUISIERA UN RESPORTE DONDE SE BUSQUE EL SUELDO MAXIMO POR DEPARTAMENTO, SIEMPRE
-- Y CUANDO ,ESTE SUELDO MAXIMO SEA MAYOR QUE , 10000.

SELECT MAX (SALARY), DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE MAX(SALARY) > 10000
GROUP BY DEPARTMENT_ID;

--NO PODEMOS USAR CLAUSULAS "WHERE" CUANDO USAMOS CLAUSULAS "GROUP BY"

SELECT MAX (SALARY)
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID;
HAVING MAX(SALARY) > 10000

--quisiera un reporte donde se busque el sueldo macimo por departamento, siempre,
--Y CUANDO, ESTE SUELDO MAXIMO SEA MAYOR QUE 10000, Y LOS DEPARTAMENTO ESTEN
--EN EL RANGO DEL 50 AL 90, ORDENAR POR DEPARTAMENTO DECENDENTE

SELECT MAX(SALARY)
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 90
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY)> 10000
ORDER BY 2 DESC;