##Tabla de ejemplo: Productos

CREATE TABLE LMLA_PRODUCTOS(
	ID_PRODUCTO NUMBER,
	NOMBRE_PRODUCTO VARCHAR2(20),
	TIPO_PRODUCTO VARCHAR2(20),
	PRECIO_PRODUCTO NUMBER,
	CONSTRAINT LMLA_PRODUCTOS PRIMARY KEY(ID_PRODUCTO)
);

##Ejercicio 1: Procedimiento para cambiar el precio de un producto

CREATE OR REPLACE PROCEDURE LMLA_ACTUALIZAR_PRECIO_PRODUCTO(
	ID_PRODUCTO_P NUMBER,
	NUEVO_PRECIO_P NUMBER
)
IS
BEGIN
	LOCK TABLE LMLA_PRODUCTOS IN ROW EXCLUSIVE MODE;
	UPDATE LMLA_PRODUCTOS
	SET PRECIO_PRODUCTO=NUEVO_PRECIO_P
	WHERE ID_PRODUCTO=ID_PRODUCTO_P;
	commit;
	EXCEPTION
        	WHEN STORAGE_ERROR THEN
	 			RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        	WHEN OTHERS THEN
           		 RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;	
END;

##Ejercicio 2: Procedimiento para crear un producto
CREATE OR REPLACE PROCEDURE LMLA_CREAR_PRODUCTO(
	ID_PRODUCTO_P NUMBER,
	NOMBRE_PRODUCTO_P VARCHAR2,
	TIPO_PRODUCTO_P VARCHAR2,
	PRECIO_PRODUCTO_P NUMBER)
IS
BEGIN
	LOCK TABLE LMLA_PRODUCTOS IN ROW EXCLUSIVE MODE;
	INSERT INTO LMLA_PRODUCTOS(ID_PRODUCTO,NOMBRE_PRODUCTO,TIPO_PRODUCTO,PRECIO_PRODUCTO)
	VALUES(ID_PRODUCTO_P,NOMBRE_PRODUCTO_P,TIPO_PRODUCTO_P,PRECIO_PRODUCTO_P);	
	commit;
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
				RAISE_APPLICATION_ERROR(-20100, 'ERROR: El ID de producto ' || ID_PRODUCTO_P || ' ya existe.');
        	WHEN STORAGE_ERROR THEN
	 			RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        	WHEN OTHERS THEN
           		 RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
	ROLLBACK;	
END;

##Ejercicio 3: Procedimiento para borrar un producto

CREATE OR REPLACE PROCEDURE LMLA_BORRAR_PRODUCTO(
	ID_PRODUCTO_P NUMBER
)
IS
BEGIN
	LOCK TABLE LMLA_PRODUCTOS IN ROW EXCLUSIVE MODE;
	DELETE FROM LMLA_PRODUCTOS
	WHERE ID_PRODUCTO=ID_PRODUCTO_P;
	commit;
	EXCEPTION
        	WHEN STORAGE_ERROR THEN
	 			RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        	WHEN OTHERS THEN
           		 RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;	
END;


##Ejercicio 4: Agrupar los procedimientos de Update, Insert y Delete en 1 solo

CREATE OR REPLACE PROCEDURE LMLA_GESTIONAR_PRODUCTOS(
	OPCION_P VARCHAR2,
	ID_PRODUCTO_P NUMBER,
	NOMBRE_PRODUCTO_P VARCHAR2 DEFAULT NULL,
	TIPO_PRODUCTO_P VARCHAR2 DEFAULT NULL,
	PRECIO_PRODUCTO_P NUMBER DEFAULT NULL
)
IS
BEGIN
	LOCK TABLE LMLA_PRODUCTOS IN ROW EXCLUSIVE MODE;
	
	IF UPPER(OPCION_P)='I' THEN
		INSERT INTO LMLA_PRODUCTOS(ID_PRODUCTO,NOMBRE_PRODUCTO,TIPO_PRODUCTO,PRECIO_PRODUCTO)
		VALUES(ID_PRODUCTO_P,NOMBRE_PRODUCTO_P,TIPO_PRODUCTO_P,PRECIO_PRODUCTO_P);

	ELSIF UPPER(OPCION_P)='D' THEN
		DELETE FROM LMLA_PRODUCTOS
		WHERE ID_PRODUCTO=ID_PRODUCTO_P;

	ELSIF UPPER(OPCION_P)='U' THEN
		UPDATE LMLA_PRODUCTOS
		SET NOMBRE_PRODUCTO=NOMBRE_PRODUCTO_P
			TIPO_PRODUCTO=TIPO_PRODUCTO_P
			PRECIO_PRODUCTO=PRECIO_PRODUCTO_P
		WHERE ID_PRODUCTO=ID_PRODUCTO_P;
	END IF;
	commit;
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
				RAISE_APPLICATION_ERROR(-20100, 'ERROR: El ID de producto ' || ID_PRODUCTO_P || ' ya existe.');
        	WHEN STORAGE_ERROR THEN
	 			RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        	WHEN OTHERS THEN
           		 RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;	
END;


BEGIN
	LMLA_GESTIONAR_PRODUCTOS('I',1,'QUIX','LIMPIEZA',1200);
END;


BEGIN
	LMLA_GESTIONAR_PRODUCTOS('U',1,'MAGISTRAL','LIMPIEZA',1200);
END;