/*
NOMBRE_ESTUDIANTE: RICARDO ANTONIO YAÑEZ VEGA
NOMBRE_PROFESOR: CARLOS CASTRO BUSTAMANTE
FECHA: 06-11
NOMBRE_RAMO: MODELAMIENTO DE DATOS
SECCION: 2

*/
------------------------------------BORRADO DE TABLAS
DROP TABLE RAYV_DETALLE_LIBRO_AUTOR;
DROP TABLE RAYV_AUTORES;
DROP TABLE RAYV_DETALLE_PRESTAMO_EJEMPLAR;
DROP TABLE RAYV_EJEMPLARES;
DROP TABLE RAYV_LIBROS;
DROP TABLE RAYV_EDITORIALES;
DROP TABLE RAYV_PRESTAMOS;
DROP TABLE RAYV_USUARIOS;
DROP TABLE RAYV_CIUDADES;
DROP TABLE RAYV_REGIONES;

------------------------------------CREACION DE TABLAS
--REPLICANDO LA TABLA DE LA BIBLIOTECA NORMALIZADA Q ESTA EN LA UNIDAD 2 DEL LMS

CREATE TABLE RAYV_EDITORIALES(
    COD_EDITORIAL NUMBER,
    NOMBRE_EDITORIAL VARCHAR2(100)
    CONSTRAINT PK_RAYV_EDITORIALES PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE RAYV_LIBROS(
    COD_LIBRO NUMBER,
    ISBN_LIBRO NUMBER,
    TITULO_LIBRO VARCHAR2(300),
    NRO_PAGINAS_LIBRO NUMBER,
    COD_EDITORIAL NUMBER,
    CONSTRAINT PK_RAYV_LIBROS PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_RAYV_LIBROS_EDITORIALES FOREIGN KEY(COD_EDITORIAL) REFERENCES RAYV_EDITORIALES(COD_EDITORIAL)
);

CREATE TABLE RAYV_AUTORES(
    COD_AUTOR NUMBER,
    NOMBRE_AUTOR VARCHAR2(200),
    APELLIDO1_AUTOR VARCHAR2(80),
    APELLIDO2_AUTOR VARCHAR2(80),
    CONSTRAINT PK_AUTORES PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE RAYV_DETALLES_LIBRO_AUTOR(
    COD_AUTOR NUMBER,
    COD_LIBRO NUMBER,
    CONSTRAINT PK_DETALLES_LIBRO_AUTOR PRIMARY KEY (COD_AUTOR,COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_LIBROS FOREIGN KEY (COD_LIBRO) REFERENCES RAYV_LIBROS(COD_LIBRO),
    CONSTRAINT FK_RAYV_DETALLES_LIBRO_AUTOR_AUTORES FOREIGN KEY (COD_AUTOR) REFERENCES RAYV_AUTORES(COD_AUTOR)
);

CREATE TABLE RAYV_EJEMPLARES(
    COD_EJEMPLAR NUMBER,
    COD_LIBRO NUMBER,
    LOCALIZACION VARCHAR2(6),
    CONSTRAINT PK_RAYV_EJEMPLARES PRIMARY KEY (COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_EJEMPLARES_LIBROS FOREIGN KEY(COD_LIBRO) REFERENCES RAYV_LIBROS(COD_LIBRO)
);

CREATE TABLE RAYV_REGIONES(
	COD_REGION NUMBER,
	NOMBRE_REGION VARCHAR2(30),
	CONSTRAINT PK_RAYV_REGIONES PRIMARY KEY(COD_REGION)
);

CREATE TABLE RAYV_CIUDADES(
	COD_CIUDAD NUMBER,
	NOMBRE_CIUDAD VARCHAR2(30),
	COD_REGION NUMBER,
	CONSTRAINT PK_RAYV_CIUDADES PRIMARY KEY(COD_CIUDAD),
	CONSTRAINT FK_RAYV_CUIUDADES_REGIONES FOREIGN KEY(COD_REGION) REFERENCES RAYV_REGIONES(COD_REGION)
);

CREATE TABLE RAYV_USUARIOS(
	COD_USUARIO NUMBER,
	NOMBRE_USUARIO VARCHAR2(200),
	APELLIDO1_USUARIO VARCHAR2(80),
	APELLIDO2_USUARIO VARCHAR2(80),
	TELEFONO_USUARIO NUMBER,
	DIRECCION_USUARIO_CALLE VARCHAR2(50),
	DIRECCION_USUARIO_NUMERO NUMBER,
	COD_CIUDAD NUMBER,
	CONSTRAINT PK_RAYV_USUARIOS PRIMARY KEY(COD_USUARIO),
	CONSTRAINT FK_RAYV_USUARIOS_CIUDADES FOREIGN KEY(COD_CIUDAD) REFERENCES RAYV_CIUDADES(COD_CIUDAD)
);

CREATE TABLE RAYV_PRESTAMOS(
	COD_PRESTAMO NUMBER,
	FECHA_PRESTAMO DATE,
	FECHA_DEVOLUCION DATE,
	COD_USUARIO NUMBER,
	CONSTRAINT PK_RAYV_PRESTAMO PRIMARY KEY(COD_PRESTAMO),
	CONSTRAINT FK_RAYV_PRESTAMO_USUARIOS FOREIGN KEY(COD_USUARIO) REFERENCES RAYV_USUARIOS(COD_USUARIO)
);

CREATE TABLE RAYV_DETALLE_PRESTAMO_EJEMPLAR(
	COD_PRESTAMO NUMBER,
	COD_EJEMPLAR NUMBER,
	CONSTRAINT PK_RAYV_DETALLE_PRESTAMO_EJEMPLAR PRIMARY KEY(COD_PRESTAMO,COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_DETALLE_PRESTAMO_EJEMPLAR_EJEMPALRES FOREIGN KEY(COD_EJEMPLAR) REFERENCES RAYV_EJEMPLARES(COD_EJEMPLAR),
	CONSTRAINT FK_RAYV_DETALLE_PRESTAMO_EJEMPLAR_PRESTAMOS FOREIGN KEY(COD_PRESTAMO) REFERENCES RAYV_PRESTAMOS(COD_PRESTAMO)
);



-----------------insert editoriales
INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
	VALUES(1,'ALFAOMEGA');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
	VALUES(2,'UCM');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
	VALUES(3,'UTALCA');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
	VALUES(4,'MCGRAWHILL');

INSERT INTO RAYV_EDITORIALES(COD_EDITORIAL,NOMBRE_EDITORIAL)
	VALUES(5,'DOLCEGUSTO');

------------------insert para libros
INSERT INTO RAYV_LIBROS(COD_LIBRO, ISBN_LIBRO,TITULO_LIBRO,NRO_PAGINAS_LIBRO,COD_EDITORIAL)
	VALUES(1,12345678,'MAGALLANES EL MEJOR EQUIPO', 150,2);

INSERT INTO RAYV_LIBROS(COD_LIBRO, ISBN_LIBRO,TITULO_LIBRO,NRO_PAGINAS_LIBRO,COD_EDITORIAL)
	VALUES(2,23456789,'BASE DE DATOS', 200,1);

INSERT INTO RAYV_LIBROS(COD_LIBRO, ISBN_LIBRO,TITULO_LIBRO,NRO_PAGINAS_LIBRO,COD_EDITORIAL)
	VALUES(3,34567890,'PYTHON FOR DUMMIES', 350,3);

INSERT INTO RAYV_LIBROS(COD_LIBRO, ISBN_LIBRO,TITULO_LIBRO,NRO_PAGINAS_LIBRO,COD_EDITORIAL)
	VALUES(4,45678901,'CALCULO III COMO SI ESTUVIERA EN PRIMERO', 1000,5);

INSERT INTO RAYV_LIBROS(COD_LIBRO, ISBN_LIBRO,TITULO_LIBRO,NRO_PAGINAS_LIBRO,COD_EDITORIAL)
	VALUES(5,56789012,'AUTOGESTIÓN PARA INFORMÁTICA', 80,4);

-----------------insert para autores
INSERT INTO RAYV_AUTORES(COD_AUTOR, NOMBRE_AUTOR,APELLIDO1_AUTOR,APELLIDO2_AUTOR)
	VALUES(1,'HUGO','ARAYA','CARRASCO');

INSERT INTO RAYV_AUTORES(COD_AUTOR, NOMBRE_AUTOR,APELLIDO1_AUTOR,APELLIDO2_AUTOR)
	VALUES(2,'CARLOS','CASTRO','BUSTAMANTE');

INSERT INTO RAYV_AUTORES(COD_AUTOR, NOMBRE_AUTOR,APELLIDO1_AUTOR,APELLIDO2_AUTOR)
	VALUES(3,'JAVIER','ROJAS','NUÑEZ');

INSERT INTO RAYV_AUTORES(COD_AUTOR, NOMBRE_AUTOR,APELLIDO1_AUTOR,APELLIDO2_AUTOR)
	VALUES(4,'LUIS','PONCE','ROSALES');

INSERT INTO RAYV_AUTORES(COD_AUTOR, NOMBRE_AUTOR,APELLIDO1_AUTOR,APELLIDO2_AUTOR)
	VALUES(5,'SERGIO','HERNANDEZ','ALVAREZ');

-----------------insert libros de autor
INSERT INTO RAYV_DETALLE_LIBRO_AUTOR(COD_AUTOR,COD_LIBRO)
	VALUES(1,1);
INSERT INTO RAYV_DETALLE_LIBRO_AUTOR(COD_AUTOR,COD_LIBRO)
	VALUES(2,1);
INSERT INTO RAYV_DETALLE_LIBRO_AUTOR(COD_AUTOR,COD_LIBRO)
	VALUES(1,2);


------------------insert ejemplares
INSERT INTO RAYV_EJEMPLARES(COD_EJEMPLAR,COD_LIBRO,LOCALIZACION)
    VALUES(1,1,'A1');
INSERT INTO RAYV_EJEMPLARES(COD_EJEMPLAR,COD_LIBRO,LOCALIZACION)
    VALUES(2,2,'A2');
INSERT INTO RAYV_EJEMPLARES(COD_EJEMPLAR,COD_LIBRO,LOCALIZACION)
    VALUES(3,3,'A3');
INSERT INTO RAYV_EJEMPLARES(COD_EJEMPLAR,COD_LIBRO,LOCALIZACION)
    VALUES(4,4,'A4');
INSERT INTO RAYV_EJEMPLARES(COD_EJEMPLAR,COD_LIBRO,LOCALIZACION)
    VALUES(5,5,'A5');

----------------insert regiones
INSERT INTO RAYV_REGIONES(COD_REGION,NOMBRE_REGION)
    VALUES(1,'ANTOFAGASTA');
INSERT INTO RAYV_REGIONES(COD_REGION,NOMBRE_REGION)
    VALUES(2,'ATACAMA');
INSERT INTO RAYV_REGIONES(COD_REGION,NOMBRE_REGION)
    VALUES(3,'COQUIMBO');
INSERT INTO RAYV_REGIONES(COD_REGION,NOMBRE_REGION)
    VALUES(4,'VALPARAISO');
INSERT INTO RAYV_REGIONES(COD_REGION,NOMBRE_REGION)
    VALUES(5,'MAULE');

---------------------insert ciudades
INSERT INTO RAYV_CIUDADES(COD_CIUDAD,NOMBRE_CIUDAD,COD_REGION)
    VALUES(1,'ANTOFAGASTA',1);
INSERT INTO RAYV_CIUDADES(COD_CIUDAD,NOMBRE_CIUDAD,COD_REGION)
    VALUES(2,'COPIAPO',2);
INSERT INTO RAYV_CIUDADES(COD_CIUDAD,NOMBRE_CIUDAD,COD_REGION)
    VALUES(3,'OVALLE',3);
INSERT INTO RAYV_CIUDADES(COD_CIUDAD,NOMBRE_CIUDAD,COD_REGION)
    VALUES(4,'SAN FELIPE',4);
INSERT INTO RAYV_CIUDADES(COD_CIUDAD,NOMBRE_CIUDAD,COD_REGION)
    VALUES(5,'TALCA',5);

-----------------insert usuarios
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(2,'HARRISON','FORD');
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(3,'LEONARDO','DICAPRIO');
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(4,'WILL','SMITH');
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(5,'TOM','CRUISE');

-----------------insert prestamos
INSERT INTO RAYV_PRESTAMOS(COD_PRESTAMO,FECHA_PRESTAMO,FECHA_DEVOLUCION,COD_USUARIO)


-----------------insert tarea aparte

--AGREGAR DATOS DEL USUARIO
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(1,'JHONNY','DEEP');
--AGREGAR PRESTAMO
INSERT INTO RAYV_PRESTAMOS(COD_PRESTAMO,FECHA_PRESTAMO,FECHA_DEVOLUCION,COD_USUARIO)
    VALUES(1,'06/11/2025','06/18/2025',1);


--MUESTRA TODOS LOS LIBROS DE RAYV_LIBROS SIEMPRE Y CUANDO LA EDITORIAL SEA MAYOR A 3
SELECT *
FROM RAYV_LIBROS
WHERE(COD_EDITORIAL > 3);

--MUESTRA TODOS PRESTAMOS DE RAYV_PRESTAMOS CUANDO LA FECHA DE PRESTAMO SEA MENOR A LA QUE NOS DICEN
SELECT *
FROM RAYV_PRESTAMOS
WHERE(FECHA_PRESTAMO < '06/17/2025');
--DEBIDO A QUE NO ENCUENTRA DATOS IGUALES A 3, SE MUESTRA EN PANTALLA QUE NO ENCONTRÓ DATOS
SELECT *
FROM RAYV_DETALLES_LIBRO_AUTOR
WHERE(COD_LIBRO = 3);
