/*
NOMBRE_ESTUDIANTE: RICARDO ANTONIO YAÑEZ VEGA
NOMBRE_PROFESOR: CARLOS CASTRO BUSTAMANTE
FECHA: 06-11
NOMBRE_RAMO: MODELAMIENTO DE DATOS
SECCION: 2

*/
------------------------------------BORRADO DE TABLAS
--AGREGAR DATOS DEL USUARIO
INSERT INTO RAYV_USUARIOS(COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO)
    VALUES(1,'JHONNY','DEEP');
--AGREGAR PRESTAMO
INSERT INTO RAYV_PRESTAMOS(COD_PRESTAMO,FECHA_PRESTAMO,FECHA_DEVOLUCION,COD_USUARIO)
    VALUES(1,'06/11/2025','06/18/2025',1);


--MUESTRA TODOS LOS LIBROS DE RAYV_LIBROS SIEMPRE Y CUANDO LA EDITORIAL SEA MAYOR A 3
SELECT *
FROM RAYV_LIBROS
WHERE(COD_EDITORIAL > 3);

--MUESTRA TODOS PRESTAMOS DE RAYV_PRESTAMOS CUANDO LA FECHA DE PRESTAMO SEA MENOR A LA QUE NOS DICEN
SELECT *
FROM RAYV_PRESTAMOS
WHERE(FECHA_PRESTAMO < '06/17/2025');
--DEBIDO A QUE NO ENCUENTRA DATOS IGUALES A 3, SE MUESTRA EN PANTALLA QUE NO ENCONTRÓ DATOS
SELECT *
FROM RAYV_DETALLES_LIBRO_AUTOR
WHERE(COD_LIBRO = 3);
