



SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID = 90;

-- QUISIERA MOSTRAR COD_EMPLEADOS ,APELLIDO , CARGO , DEPARTAMENTO Y
-- FECHA DE CONTRATACION DE TODOS AQUELLOS EMPLEADOS QUE FUERON CONTRATADOS DESPUES
-- DEL AÑO 2015

























-- QUISIERA MOSTRAR COD_EMPLEADOS , APELLIDO ,CARGO Y DEPARTAMENTO
--DE LA EMPLEADA WHALEN.
SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE LAST_NAME = 'Whalen';

--CUANDO NO HAY CLARIDAD ,ASOCIADA A SI WHALEN ES NOMBRE O APELLIDO,
--DEBO GENERAR UNA BOBLE RESTRICCION UNIDA CON UN OPERADOR LOGICO .
--ENSQL SE TRABAJA CON SUS EXPRESIONES LITELARES : AND OR NOT

SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE FIRST_NAME = 'Whalen' or LAST_NAME = 'Whalen';


--QUISIERA MOSTRAR COD_EMPLEADOS,APELLIDO ,CARGO Y DEPARTAMENTO
--DE TODOS AQUELLOS EMPLEADOS Q GANEN ENTRE 3000 Y 5000 USD

SELECT EMPLOYEE_ID ,LAST_NAME, JOB_ID , DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE SALARY >= 3000 AND SALARY <= 5000;

--EL OPERADOR BETWEEN ME PERMITE FILTRAR DATOS DE ACUERDO AUN RANGO
--VALORES , PENSANDO EN LIMITE INFERIOR Y UN LIMITE SUPERIOR
-- CORRESPONDIENTEMENTE , QUEDANDO COMO CONDICION
--WHERE (CAMPO RESTRINGIO BETWEEN LIM_INF AND LIM_SUP)

